window.districtAssemblyMap = {
  "Ariyalur": ["Ariyalur", "Jayankondam"],
  "Chengalpattu": ["Chengalpattu", "Cheyyur", "Madurantakam", "Pallavaram", "Sholinganallur", "Tambaram", "Thiruporur"],
  "Chennai": ["Anna Nagar", "Chepauk-Thiruvallikeni", "Dr. Radhakrishnan Nagar", "Egmore", "Harbour", "Kolathur", "Mylapore", "Perambur", "Royapuram", "Saidapet", "Thiru-Vi-Ka-Nagar", "Thiyagarayanagar", "Thousand Lights", "Velachery", "Villivakkam", "Virugampakkam"],
  "Coimbatore": ["Coimbatore (North)", "Coimbatore (South)", "Kavundampalayam", "Kinathukadavu", "Mettupalayam", "Pollachi", "Singanallur", "Sulur", "Thondamuthur", "Valparai"],
  "Cuddalore": ["Bhuvanagiri", "Chidambaram", "Cuddalore", "Kattumannarkoil", "Kurinjipadi", "Neyveli", "Panruti", "Tittakudi", "Vridhachalam"],
  "Dharmapuri": ["Dharmapuri", "Harur", "Palacode", "Pappireddipatti", "Pennagaram"],
  "Dindigul": ["Athoor", "Dindigul", "Natham", "Nilakkottai", "Oddanchatram", "Palani", "Vedasandur"],
  "Erode": ["Anthiyur", "Bhavani", "Bhavanisagar", "Erode (East)", "Erode (West)", "Gobichettipalayam", "Modakkurichi", "Perundurai"],
  "Kallakurichi": ["Kallakurichi", "Rishivandiyam", "Sankarapuram", "Ulundurpettai"],
  "Kancheepuram": ["Alandur", "Kancheepuram", "Sriperumbudur", "Uthiramerur"],
  "Kanyakumari": ["Colachal", "Kanniyakumari", "Killiyoor", "Nagercoil", "Padmanabhapuram", "Vilavancode"],
  "Karur": ["Aravakurichi", "Karur", "Krishnarayapuram", "Kulithalai"],
  "Krishnagiri": ["Bargur", "Hosur", "Krishnagiri", "Thally", "Uthangarai", "Veppanahalli"],
  "Madurai": ["Madurai Central", "Madurai East", "Madurai North", "Madurai South", "Madurai West", "Melur", "Sholavandan", "Thirumangalam", "Thiruparankundram", "Usilampatti"],
  "Mayiladuthurai": ["Mayiladuthurai", "Poompuhar", "Sirkazhi"],
  "Nagapattinam": ["Kilvelur", "Nagapattinam", "Vedaranyam"],
  "Namakkal": ["Kumarapalayam", "Namakkal", "Paramathivelur", "Rasipuram", "Senthamangalam", "Tiruchengodu"],
  "Nilgiris": ["Coonoor", "Gudalur", "Udhagamandalam (Ooty)"],
  "Perambalur": ["Kunnam", "Perambalur"],
  "Pudukkottai": ["Alangudi", "Aranthangi", "Gandarvakottai", "Pudukkottai", "Thirumayam", "Viralimalai"],
  "Ramanathapuram": ["Mudukulathur", "Paramakudi", "Ramanathapuram", "Tiruvadanai"],
  "Ranipet": ["Arakkonam", "Arcot", "Ranipet", "Sholinghur"],
  "Salem": ["Attur", "Edappadi", "Gangavalli", "Mettur", "Omalur", "Salem (North)", "Salem (South)", "Salem (West)", "Sankari", "Veerapandi", "Yercaud"],
  "Sivaganga": ["Karaikudi", "Manamadurai", "Sivaganga", "Tiruppathur"],
  "Tenkasi": ["Alangulam", "Kadayanallur", "Sankarankovil", "Tenkasi", "Vasudevanallur"],
  "Thanjavur": ["Kumbakonam", "Orathanadu", "Papanasam", "Pattukkottai", "Peravurani", "Thanjavur", "Thiruvaiyaru", "Thiruvidaimarudur"],
  "Theni": ["Andipatti", "Bodinayakanur", "Cumbum", "Periyakulam"],
  "Thoothukudi": ["Kovilpatti", "Ottapidaram", "Srivaikuntam", "Thoothukudi", "Tiruchendur", "Vilathikulam"],
  "Tiruchirappalli": ["Lalgudi", "Manachanallur", "Manapparai", "Musiri", "Srirangam", "Thiruverumbur", "Thuraiyur", "Tiruchirappalli (East)", "Tiruchirappalli (West)"],
  "Tirunelveli": ["Ambasamudram", "Nanguneri", "Palayamkottai", "Radhapuram", "Tirunelveli"],
  "Tirupathur": ["Ambur", "Jolarpet", "Tirupattur", "Vaniyambadi"],
  "Tiruppur": ["Avanashi", "Dharapuram", "Kangayam", "Madathukulam", "Palladam", "Tiruppur (North)", "Tiruppur (South)", "Udumalaipettai"],
  "Tiruvallur": ["Ambattur", "Avadi", "Gummidipoondi", "Madhavaram", "Maduravoyal", "Ponneri", "Poonamallee", "Thiruvallur", "Thiruvottiyur", "Tiruttani"],
  "Tiruvannamalai": ["Arani", "Chengam", "Cheyyar", "Kalasapakkam", "Kilpennathur", "Polur", "Tiruvannamalai", "Vandavasi"],
  "Tiruvarur": ["Mannargudi", "Nannilam", "Thiruthuraipoondi", "Tiruvarur"],
  "Vellore": ["Anaikattu", "Gudiyattam", "Katpadi", "Kilvaithinankuppam", "Vellore"],
  "Viluppuram": ["Gingee", "Mailam", "Tindivanam", "Tirukkoyilur", "Vanur", "Vikravandi", "Villupuram"],
  "Virudhunagar": ["Aruppukottai", "Rajapalayam", "Sattur", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Virudhunagar"]
};

window.districtTalukMap = {
  "Ariyalur": ["Ariyalur", "Sendurai", "Udayarpalayam", "T.Palur"],
  "Chengalpattu": ["Chengalpattu", "Cheyyur", "Madurantakam", "Tambaram", "Thirukazhukundram", "Vandalur"],
  "Chennai": ["Alandur", "Egmore-Nungambakkam", "Mambalam-Guindy", "Perambur-Purasawalkam", "Royapuram", "Sholinganallur", "Tiruvottiyur"],
  "Coimbatore": ["Anaimalai", "Annur", "Coimbatore North", "Coimbatore South", "Kinathukadavu", "Mettupalayam", "Pollachi", "Sulur", "Valparai"],
  "Cuddalore": ["Bhuvanagiri", "Chidambaram", "Cuddalore", "Kattumannarkoil", "Kurinjipadi", "Panruti", "Titakudi", "Vriddachalam"],
  "Dharmapuri": ["Dharmapuri", "Harur", "Karimangalam", "Nallampalli", "Palacode", "Pappireddipatti", "Pennagaram"],
  "Dindigul": ["Dindigul", "Kodaikanal", "Natham", "Nilakottai", "Oddanchattiram", "Palani", "Vedasandur"],
  "Erode": ["Anthiyur", "Bhavani", "Erode", "Gobichettipalayam", "Nambiyur", "Perundurai", "Sathyamangalam"],
  "Kallakurichi": ["Chinnasalem", "Kallakkurichi", "Sankarapuram", "Thirukoilur", "Ulundurpet"],
  "Kancheepuram": ["Kancheepuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
  "Kanyakumari": ["Agastheeswaram", "Kalkulam", "Thovalai", "Vilavancode"],
  "Karur": ["Aravakurichi", "Kadavur", "Karur", "Krishnarayapuram", "Kulithalai", "Manmangalam", "Pugalur"],
  "Krishnagiri": ["Bargur", "Denkanikottai", "Hosur", "Krishnagiri", "Pochampalli", "Shoolagiri", "Uthangarai"],
  "Madurai": ["Madurai North", "Madurai South", "Melur", "Peraiyur", "Thirumangalam", "Usilampatti", "Vadipatti"],
  "Mayiladuthurai": ["Kuthalam", "Mayiladuthurai", "Sirkazhi", "Tarangambadi"],
  "Nagapattinam": ["Kilvelur", "Nagapattinam", "Tirukuvalai", "Vedaranyam"],
  "Namakkal": ["Kolli Hills", "Kumarapalayam", "Mohanur", "Namakkal", "Paramathi Velur", "Rasipuram", "Tiruchengode"],
  "Nilgiris": ["Coonoor", "Gudalur", "Kotagiri", "Kundah", "Pandalur", "Udhagamandalam"],
  "Perambalur": ["Alathur", "Kunnam", "Perambalur", "Veppanthattai"],
  "Pudukkottai": ["Alangudi", "Aranthangi", "Avudaiyarkoil", "Gandarvakottai", "Illuppur", "Karambakkudi", "Kulathur", "Manamelkudi", "Ponnamaravathi", "Pudukkottai", "Thirumayam", "Viralimalai"],
  "Ramanathapuram": ["Kadaladi", "Kamuthi", "Kilakarai", "Mudukulathur", "Paramakudi", "Ramanathapuram", "Rameswaram", "Tiruvadanai"],
  "Ranipet": ["Arakkonam", "Arcot", "Nemili", "Sholingur", "Walajah"],
  "Salem": ["Attur", "Edappadi", "Gangavalli", "Kadayampatti", "Mettur", "Omalur", "Salem", "Sankari", "Yercaud"],
  "Sivaganga": ["Devakottai", "Ilayangudi", "Kalaiyarkoil", "Karaikudi", "Manamadurai", "Sivaganga", "Tirupathur"],
  "Tenkasi": ["Alangulam", "Kadayanallur", "Sankarankoil", "Sengottai", "Tenkasi", "Veerakeralampudur"],
  "Thanjavur": ["Budalur", "Kumbakonam", "Orathanadu", "Papanasam", "Pattukkottai", "Peravurani", "Thanjavur", "Thiruvaiyaru", "Thiruvidaimarudur"],
  "Theni": ["Andipatti", "Bodinayakanur", "Periyakulam", "Theni", "Uthamapalayam"],
  "Thoothukudi": ["Eral", "Ettayapuram", "Kovilpatti", "Ottapidaram", "Sathankulam", "Srivaikuntam", "Thoothukudi", "Tiruchendur"],
  "Tiruchirappalli": ["Lalgudi", "Manapparai", "Marungapuri", "Musiri", "Srirangam", "Thuraiyur", "Tiruchirappalli"],
  "Tirunelveli": ["Ambasamudram", "Cheranmahadevi", "Manur", "Nanguneri", "Palayamkottai", "Radhapuram", "Tirunelveli"],
  "Tirupathur": ["Ambur", "Natrampalli", "Tirupathur", "Vaniyambadi"],
  "Tiruppur": ["Avinashi", "Dharapuram", "Kangeyam", "Madathukulam", "Palladam", "Tiruppur", "Udumalpet", "Uthukuli"],
  "Tiruvallur": ["Avadi", "Gummidipoondi", "Pallipattu", "Ponneri", "Poonamallee", "Thiruvallur", "Tiruttani", "Uthukkottai"],
  "Tiruvannamalai": ["Arni", "Chengam", "Cheyyar", "Chetpet", "Kilpennathur", "Polur", "Thandrampet", "Tiruvannamalai", "Vandavasi"],
  "Tiruvarur": ["Kodavasal", "Koothanallur", "Mannargudi", "Nannilam", "Needamangalam", "Thiruthuraipoondi", "Tiruvarur"],
  "Vellore": ["Anaicut", "Gudiyatham", "K.V. Kuppam", "Katpadi", "Pernambut", "Vellore"],
  "Viluppuram": ["Gingee", "Kallakurichi", "Marakkanam", "Tindivanam", "Tiruvennainallur", "Vikravandi", "Viluppuram"],
  "Virudhunagar": ["Aruppukottai", "Kariapatti", "Rajapalayam", "Sattur", "Sivakasi", "Srivilliputhur", "Virudhunagar"]
};
